# ---------------------------
# Conexiune la Brocade Switch
# ---------------------------
credential:
  fos_ip_addr: "{{ ansible_host }}"
  fos_user_name: "{{ san_user }}"
  fos_password: "{{ san_password }}"
  https: False
  ssh_hostkeymust: False   # parametru oficial

# vfid TREBUIE să fie la nivel de modul, nu în credential
vfid: -1


# ---------------------------
# Configurație Zoning globală
# ---------------------------
cfg_name: "fcsw1_bc"
